
import React from 'react';

export const TRANSLATIONS = {
  en: {
    home: 'Home',
    myAirdrops: 'My Airdrops',
    calendar: 'Calendar',
    claims: 'Claims',
    admin: 'Admin Panel',
    connectWallet: 'Connect Wallet',
    profile: 'Profile',
    usernamePrompt: 'Choose a Username',
    save: 'Save',
    investment: 'Investment',
    type: 'Type',
    free: 'Free',
    paid: 'Paid',
    rating: 'Rating',
    addAirdrop: 'Request Airdrop',
    addCustom: 'Add Custom Airdrop',
    guides: 'Guides',
    comments: 'Comments',
    todo: 'To-Do List',
    myDay: 'My Day',
    deadline: 'Deadline',
    reminder: 'Reminder',
    none: 'None',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    allLanguages: 'All Languages',
    addGuide: 'Request Guide',
    sendRequest: 'Send Request',
    welcome: 'Welcome back',
    noEvents: 'No events scheduled for today.',
    upcomingClaims: 'Upcoming Claims',
    daysLeft: 'days left',
    expired: 'Expired',
    adminTools: 'Admin Tools',
    users: 'Users',
    requests: 'Requests',
    ban: 'Ban',
    approve: 'Approve',
  },
  tr: {
    home: 'Ana Sayfa',
    myAirdrops: 'Airdroplarım',
    calendar: 'Takvim',
    claims: 'Claimler',
    admin: 'Yönetici Paneli',
    connectWallet: 'Cüzdan Bağla',
    profile: 'Profil',
    usernamePrompt: 'Kullanıcı Adı Seç',
    save: 'Kaydet',
    investment: 'Yatırım',
    type: 'Tür',
    free: 'Ücretsiz',
    paid: 'Ücretli',
    rating: 'Puan',
    addAirdrop: 'Airdrop Talebi',
    addCustom: 'Özel Airdrop Ekle',
    guides: 'Rehberler',
    comments: 'Yorumlar',
    todo: 'Yapılacaklar',
    myDay: 'Günüm',
    deadline: 'Son Tarih',
    reminder: 'Hatırlatıcı',
    none: 'Yok',
    daily: 'Günlük',
    weekly: 'Haftalık',
    monthly: 'Aylık',
    allLanguages: 'Tüm Diller',
    addGuide: 'Rehber Talebi',
    sendRequest: 'Talep Gönder',
    welcome: 'Tekrar hoşgeldin',
    noEvents: 'Bugün için planlanmış bir etkinlik yok.',
    upcomingClaims: 'Yaklaşan Claimler',
    daysLeft: 'gün kaldı',
    expired: 'Süresi Doldu',
    adminTools: 'Yönetici Araçları',
    users: 'Kullanıcılar',
    requests: 'Talepler',
    ban: 'Yasakla',
    approve: 'Onayla',
  }
};

export const FLAGS: Record<string, string> = {
  en: '🇺🇸',
  us: '🇺🇸',
  tr: '🇹🇷',
  de: '🇩🇪',
  fr: '🇫🇷',
};

export const RANDOM_AVATARS = [
  'https://picsum.photos/seed/1/200',
  'https://picsum.photos/seed/2/200',
  'https://picsum.photos/seed/3/200',
  'https://picsum.photos/seed/4/200',
  'https://picsum.photos/seed/5/200',
  'https://picsum.photos/seed/6/200',
  'https://picsum.photos/seed/7/200',
  'https://picsum.photos/seed/8/200',
];
